### ISSUE TITLE
What if the reviewer compares your results with LHRS-Bot?

### ISSUE THREAD

**Issue by zytx121** [opendatalab/VHM#4]
Don't worry, they achieved high scores on the RSVG and DIOR-RSVG datasets because there were bugs in the evaluation code...

Ref https://github.com/NJU-LHRS/LHRS-Bot/issues/27

**Comment by fitzpchao** [comment]
We noticed early on that in this VG task, resizing 800x800 images to 224x224 still yielded very high metrics, which is clearly unreasonable. In March, we even contacted the related author via email, but unfortunately, we did not receive any attention. Ironically, the reviewers we encountered also did not pay attention to this issue.
